
server:
  port: 8002

spring:
  application:
    name: owner_service
  datasource:
    #url: jdbc:mysql://localhost/petclinic_ms_owner
    url: jdbc:mysql://localhost:3306/petclinic_ms_owner?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: petclinic